food/urls.py
from . import views
from django.urls import path

app_name='food'
urlpatterns=[
    path('',views.index,name='index'),
    path('<int:item_id>/',views.detail,name='detail'),
    path('item/',views.item,name='item'),
    path('add',views.create_item,name='create_item'),
    path('update/<int:id>/',views.update_item,name="update_item"),
    path('delete/<int:id>',views.delete_item,name='delete_item'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include,path
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('food.urls')),
    path('register/',user_views.register,name="register"),
]

urls.py
from . import views
from django.urls import path


urlpatterns=[
    path('hello/',views.index,name='index')
]

food/models.py
from django.db import models

# Create your models here.
class Item(models.Model):
    def __str__(self):
        return self.item_name
    item_name=models.CharField(max_length=200)
    item_desc=models.CharField(max_length=200)
    item_price=models.IntegerField()
    item_image=models.CharField(max_length=500,default="https://wurtsmithairmuseum.net/wp-content/uploads/2018/10/Image_Coming_Soon.jpg")

users/models.py
from django.db import models

# Create your models here.

food/forms.py
from django import forms

from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model=Item
        fields=['item_name','item_desc','item_price','item_image']

food/views.py
from django.http import HttpResponse
from .models import Item
from django.template import loader
from django.shortcuts import render,redirect
from .forms import ItemForm
# Create your views here.
def index(req):
    item_list=Item.objects.all()
    template = loader.get_template('food/index.html')
    context ={
       'item_list': item_list,
    }
    # return HttpResponse(template.render(context,req))
    return render(req, 'food/index.html ',context)
def item(request):
    return HttpResponse('This is an item view ')

def detail(request,item_id):
    item=Item.objects.get(pk=item_id)
    context={
        'item':item,
    }
    # return HttpResponse("This is item no/id: %s"%item_id)
    return render(request, 'food/detail.html ',context)

def create_item(request):
    form=ItemForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request, 'food/item-form.html',{'form':form})


def update_item(request,id):
    item=Item.objects.get(id=id)
    form=ItemForm(request.POST or None,instance=item)
    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request,'food/item-form.html',{'form':form,'item':item})

def delete_item(request,id):
    item=Item.objects.get(id=id)

    if request.method =='POST':
        item.delete()
        return redirect('food:index')
    
    return render(request,'food/item-delete.html',{'item':item})

users/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm

# Create your views here.


def register(request):
    form=UserCreationForm()
    return render (request,'users/register.html',{'form':form})

views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
def index(req):
    return HttpResponse('Hi')

food/templates/food/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<link rel ="stylesheet" href="{% static 'food/style.css' %}">

<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script> 
<body>
        <nav class="navbar fixed-top navbar-dark bg-dark" >
                <a href="/food/" style="font-weight:bold;" class="navbar-brand">FoodVilla</a>
                
                <div class="navbar" >
                    <a class="nav-item nav-link"  style="text-shadow:1px 1px 1px white; " href="{%url 'food:create_item' %}">
                        Add Item
                
                    </a>
                    <a class="nav-item nav-link" href="#" style="text-shadow:1px 1px 1px white; ">
                        Delete Item
                    
                        </a>
                 <a class="nav-item nav-link" href="#" style="text-shadow:1px 1px 1px white;">
                        View Item
                        
                </a>
                </div>
                </nav>
   {% block body %}
   {% endblock %}
</body>
</html>

food/templates/food/detail.html
{% extends 'food/base.html' %}
{% block body %}

<div class="container">
    <div class="row" >
        <div class="col-md-6" style="position:absolute; top:50px;">
                <img class="card" height="300px" width="300px"   src="{{item.item_image}}">

        </div>
        <div class="col-md-6" style="position:absolute; top:400px;" >
                <h1>
                        {{item.item_name}}
                    </h1>
                    
                    <h2>
                        {{item.item_desc}}
                    </h2>
                    
                    <h3>
                        Rs. {{item.item_price}}
                    </h3>
                <a class="btn btn-danger" href="{% url 'food:delete_item' item.id %}">Delete</a>

            </div>
    

    </div>

</div>



{% endblock %}

food/templates/food/index.html
{% extends 'food/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<body>

        {% block body %}

        {% for item in item_list %}
    <div class="row" style="  margin:2rem;position:relative;top:3.5rem;">
        <div style="margin-right:5px " class="col-md-3 offset-md-2">
    
    <img class="card" height="150px" width="180px"  src="{{item.item_image}}">
        </div>
        <div class="col-md-4">
    <h3>{{item.item_name}}</h3>
    <h5>{{item.item_desc}}</h5>
    <h6>Rs.{{item.item_price}}</h6>
            </div>
    
        <div class="col-md-2">
    <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
        </div>
    
    </div>
    
        {% endfor %}
        {% endblock %}

</body>
</html>

food/templates/food/item-delete.html
{% extends 'food/base.html' %}
{% block body %}

<form method="POST" style="margin:auto; position:absolute; top:5rem;">
    {% csrf_token%}
    <h2>Are you sure you want to delete {{item.item_name}}</h2>
    <button class="btn btn-success" type="submit" >Confirm</button>
</form>

{% endblock %}

food/templates/food/item-form.html
{% extends 'food/base.html' %}
{% block body %}
<form method="POST" class="form-control" style="margin:auto;position: relative;top:4rem; display:flex; flex-direction:column; width:50% ;align-items:center;" >
    <!-- cross side scripting -->
    {% csrf_token%}
    {{form}}
    <button  type="submit" class="btn btn-primary">Save</button>
</form>

{%endblock%}

users/templates/users/register.html
<form method="POST">
    {% csrf_token %}

    {{form}}

    <button type="submit">Sign Up</button>

</form>